using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoPartsHub.Infra.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ------------------------------------------------------------------
            // Tabelas que já existem no banco — criadas via SQL direto com
            // IF NOT EXISTS para idempotência (banco foi provisionado antes do EF).
            // ------------------------------------------------------------------

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS estados (
                    codigo_uf integer NOT NULL,
                    uf character varying(2) NOT NULL,
                    nome character varying(100) NOT NULL,
                    latitude double precision NOT NULL,
                    longitude double precision NOT NULL,
                    regiao character varying(12) NOT NULL,
                    CONSTRAINT pk_estados PRIMARY KEY (codigo_uf)
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS municipios (
                    codigo_ibge integer NOT NULL,
                    nome character varying(100) NOT NULL,
                    latitude double precision NOT NULL,
                    longitude double precision NOT NULL,
                    capital boolean NOT NULL,
                    codigo_uf integer NOT NULL,
                    siafi_id character varying(4) NOT NULL,
                    ddd integer NOT NULL,
                    fuso_horario character varying(32) NOT NULL,
                    CONSTRAINT pk_municipios PRIMARY KEY (codigo_ibge),
                    CONSTRAINT fk_municipios_estados_codigo_uf FOREIGN KEY (codigo_uf)
                        REFERENCES estados (codigo_uf) ON DELETE RESTRICT
                );
                CREATE INDEX IF NOT EXISTS ix_municipios_codigo_uf ON municipios (codigo_uf);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS roles (
                    id uuid NOT NULL,
                    name character varying(256),
                    normalized_name character varying(256),
                    concurrency_stamp text,
                    CONSTRAINT pk_roles PRIMARY KEY (id)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""RoleNameIndex"" ON roles (normalized_name);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS usuarios (
                    id uuid NOT NULL,
                    tenant_id uuid NOT NULL,
                    nome_completo character varying(200) NOT NULL,
                    telefone character varying(20),
                    limite_aprovacao numeric(18,2) NOT NULL,
                    ultimo_login_em timestamp with time zone,
                    user_name character varying(256),
                    normalized_user_name character varying(256),
                    email character varying(256),
                    normalized_email character varying(256),
                    email_confirmed boolean NOT NULL,
                    password_hash text,
                    security_stamp text,
                    concurrency_stamp text,
                    phone_number text,
                    phone_number_confirmed boolean NOT NULL,
                    two_factor_enabled boolean NOT NULL,
                    lockout_end timestamp with time zone,
                    lockout_enabled boolean NOT NULL,
                    access_failed_count integer NOT NULL,
                    CONSTRAINT pk_usuarios PRIMARY KEY (id)
                );
                CREATE INDEX IF NOT EXISTS ""EmailIndex"" ON usuarios (normalized_email);
                CREATE UNIQUE INDEX IF NOT EXISTS ""UserNameIndex"" ON usuarios (normalized_user_name);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS role_claims (
                    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    role_id uuid NOT NULL,
                    claim_type text,
                    claim_value text,
                    CONSTRAINT pk_role_claims PRIMARY KEY (id),
                    CONSTRAINT fk_role_claims_roles_role_id FOREIGN KEY (role_id)
                        REFERENCES roles (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ix_role_claims_role_id ON role_claims (role_id);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS usuario_claims (
                    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    user_id uuid NOT NULL,
                    claim_type text,
                    claim_value text,
                    CONSTRAINT pk_usuario_claims PRIMARY KEY (id),
                    CONSTRAINT fk_usuario_claims_usuarios_user_id FOREIGN KEY (user_id)
                        REFERENCES usuarios (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ix_usuario_claims_user_id ON usuario_claims (user_id);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS usuario_logins (
                    login_provider text NOT NULL,
                    provider_key text NOT NULL,
                    provider_display_name text,
                    user_id uuid NOT NULL,
                    CONSTRAINT pk_usuario_logins PRIMARY KEY (login_provider, provider_key),
                    CONSTRAINT fk_usuario_logins_usuarios_user_id FOREIGN KEY (user_id)
                        REFERENCES usuarios (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ix_usuario_logins_user_id ON usuario_logins (user_id);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS usuario_roles (
                    user_id uuid NOT NULL,
                    role_id uuid NOT NULL,
                    CONSTRAINT pk_usuario_roles PRIMARY KEY (user_id, role_id),
                    CONSTRAINT fk_usuario_roles_roles_role_id FOREIGN KEY (role_id)
                        REFERENCES roles (id) ON DELETE CASCADE,
                    CONSTRAINT fk_usuario_roles_usuarios_user_id FOREIGN KEY (user_id)
                        REFERENCES usuarios (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ix_usuario_roles_role_id ON usuario_roles (role_id);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS usuario_tokens (
                    user_id uuid NOT NULL,
                    login_provider text NOT NULL,
                    name text NOT NULL,
                    value text,
                    CONSTRAINT pk_usuario_tokens PRIMARY KEY (user_id, login_provider, name),
                    CONSTRAINT fk_usuario_tokens_usuarios_user_id FOREIGN KEY (user_id)
                        REFERENCES usuarios (id) ON DELETE CASCADE
                );
            ");

            // Tabela tenants — cria se não existir, depois adiciona colunas novas
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS tenants (
                    id uuid NOT NULL,
                    razao_social character varying(200) NOT NULL,
                    nome_fantasia character varying(200) NOT NULL,
                    cnpj character varying(14) NOT NULL,
                    email character varying(256) NOT NULL,
                    tipo character varying(20) NOT NULL,
                    status character varying(30) NOT NULL,
                    plano character varying(20) NOT NULL,
                    trial_expira_em timestamp with time zone NOT NULL,
                    assinatura_renova_em timestamp with time zone,
                    cotacoes_usadas_no_ciclo integer NOT NULL,
                    latitude double precision,
                    longitude double precision,
                    end_cep character varying(8) NOT NULL DEFAULT '',
                    end_logradouro character varying(200) NOT NULL DEFAULT '',
                    end_numero character varying(20) NOT NULL DEFAULT '',
                    end_complemento character varying(100),
                    end_bairro character varying(100) NOT NULL DEFAULT '',
                    end_codigo_ibge integer NOT NULL DEFAULT 0,
                    end_codigo_uf integer NOT NULL DEFAULT 0,
                    tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
                    criado_em timestamp with time zone NOT NULL DEFAULT now(),
                    atualizado_em timestamp with time zone,
                    excluido_em timestamp with time zone,
                    CONSTRAINT pk_tenants PRIMARY KEY (id)
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ix_tenants_cnpj ON tenants (cnpj);
            ");

            // Colunas de onboarding — adicionadas apenas se não existirem
            migrationBuilder.Sql(@"
                ALTER TABLE tenants
                    ADD COLUMN IF NOT EXISTS tipo_comprador character varying(40),
                    ADD COLUMN IF NOT EXISTS plano_atual character varying(20) NOT NULL DEFAULT 'Free',
                    ADD COLUMN IF NOT EXISTS assinatura_status character varying(20) NOT NULL DEFAULT 'Free',
                    ADD COLUMN IF NOT EXISTS trial_expira_em_novo timestamp with time zone,
                    ADD COLUMN IF NOT EXISTS cotacoes_limite_mes integer NOT NULL DEFAULT 10,
                    ADD COLUMN IF NOT EXISTS usuarios_limite integer NOT NULL DEFAULT 1,
                    ADD COLUMN IF NOT EXISTS inscricao_estadual character varying(30),
                    ADD COLUMN IF NOT EXISTS telefone_comercial character varying(20) NOT NULL DEFAULT '',
                    ADD COLUMN IF NOT EXISTS como_nos_conheceu character varying(40),
                    ADD COLUMN IF NOT EXISTS descricao_outro text,
                    ADD COLUMN IF NOT EXISTS segmento_frota character varying(40),
                    ADD COLUMN IF NOT EXISTS qtd_veiculos_estimada integer,
                    ADD COLUMN IF NOT EXISTS limite_aprovacao_admin numeric(18,2),
                    ADD COLUMN IF NOT EXISTS endereco_cep character varying(9),
                    ADD COLUMN IF NOT EXISTS endereco_logradouro character varying(200),
                    ADD COLUMN IF NOT EXISTS endereco_numero character varying(20),
                    ADD COLUMN IF NOT EXISTS endereco_complemento character varying(100),
                    ADD COLUMN IF NOT EXISTS endereco_bairro character varying(100),
                    ADD COLUMN IF NOT EXISTS endereco_cidade character varying(100),
                    ADD COLUMN IF NOT EXISTS endereco_estado character varying(2);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS tenant_telefones (
                    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    valor character varying(11) NOT NULL,
                    tipo character varying(10) NOT NULL,
                    tenant_id uuid NOT NULL,
                    CONSTRAINT pk_tenant_telefones PRIMARY KEY (id),
                    CONSTRAINT fk_tenant_telefones_tenants_tenant_id FOREIGN KEY (tenant_id)
                        REFERENCES tenants (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ix_tenant_telefones_tenant_id ON tenant_telefones (tenant_id);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS refresh_tokens (
                    id uuid NOT NULL,
                    token_hash character varying(64) NOT NULL,
                    usuario_id uuid NOT NULL,
                    expira_em timestamp with time zone NOT NULL,
                    usado_em timestamp with time zone,
                    revogado boolean NOT NULL,
                    tenant_id uuid NOT NULL,
                    criado_em timestamp with time zone NOT NULL DEFAULT now(),
                    atualizado_em timestamp with time zone,
                    excluido_em timestamp with time zone,
                    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
                    CONSTRAINT fk_refresh_tokens_usuarios_usuario_id FOREIGN KEY (usuario_id)
                        REFERENCES usuarios (id) ON DELETE CASCADE
                );
                DO $$ BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns
                               WHERE table_name='refresh_tokens' AND column_name='token_hash') THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='ux_refresh_tokens_token_hash') THEN
                            CREATE UNIQUE INDEX ux_refresh_tokens_token_hash ON refresh_tokens (token_hash);
                        END IF;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns
                               WHERE table_name='refresh_tokens' AND column_name='revogado') THEN
                        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='ix_refresh_tokens_usuario_id_revogado') THEN
                            CREATE INDEX ix_refresh_tokens_usuario_id_revogado ON refresh_tokens (usuario_id, revogado);
                        END IF;
                    END IF;
                END $$;
            ");

            // ------------------------------------------------------------------
            // Tabelas NOVAS — não existiam antes desta migration
            // ------------------------------------------------------------------

            migrationBuilder.CreateTable(
                name: "onboarding_rascunho",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    session_token = table.Column<Guid>(type: "uuid", nullable: false),
                    tipo_perfil = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    ultimo_step = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    dados = table.Column<string>(type: "jsonb", nullable: false, defaultValue: "{}"),
                    email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    ip_origem = table.Column<string>(type: "text", nullable: true),
                    user_agent = table.Column<string>(type: "text", nullable: true),
                    criado_em = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "now()"),
                    atualizado_em = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_onboarding_rascunho", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_onboarding_rascunho_criado_em",
                table: "onboarding_rascunho",
                column: "criado_em");

            migrationBuilder.CreateIndex(
                name: "ix_onboarding_rascunho_email",
                table: "onboarding_rascunho",
                column: "email",
                filter: "email IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_onboarding_rascunho_session_token",
                table: "onboarding_rascunho",
                column: "session_token",
                unique: true);

            migrationBuilder.CreateTable(
                name: "cotacao_uso_mensal",
                columns: table => new
                {
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    ano_mes = table.Column<string>(type: "char(7)", nullable: false),
                    total_cotacoes = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    atualizado_em = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_cotacao_uso_mensal", x => new { x.tenant_id, x.ano_mes });
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "cotacao_uso_mensal");
            migrationBuilder.DropTable(name: "onboarding_rascunho");

            migrationBuilder.Sql(@"
                ALTER TABLE tenants
                    DROP COLUMN IF EXISTS tipo_comprador,
                    DROP COLUMN IF EXISTS plano_atual,
                    DROP COLUMN IF EXISTS assinatura_status,
                    DROP COLUMN IF EXISTS trial_expira_em_novo,
                    DROP COLUMN IF EXISTS cotacoes_limite_mes,
                    DROP COLUMN IF EXISTS usuarios_limite,
                    DROP COLUMN IF EXISTS inscricao_estadual,
                    DROP COLUMN IF EXISTS telefone_comercial,
                    DROP COLUMN IF EXISTS como_nos_conheceu,
                    DROP COLUMN IF EXISTS descricao_outro,
                    DROP COLUMN IF EXISTS segmento_frota,
                    DROP COLUMN IF EXISTS qtd_veiculos_estimada,
                    DROP COLUMN IF EXISTS limite_aprovacao_admin,
                    DROP COLUMN IF EXISTS endereco_cep,
                    DROP COLUMN IF EXISTS endereco_logradouro,
                    DROP COLUMN IF EXISTS endereco_numero,
                    DROP COLUMN IF EXISTS endereco_complemento,
                    DROP COLUMN IF EXISTS endereco_bairro,
                    DROP COLUMN IF EXISTS endereco_cidade,
                    DROP COLUMN IF EXISTS endereco_estado;
            ");
        }
    }
}
